### ISSUE TITLE
doubt about the approach taken

### ISSUE THREAD

**Issue by vncsalencar** [Multirious/helix-win-runner#1]
Hey @Multirious I just wanted to ask about why you approached this using macros and automation
I had a similar issue, I wanted to use helix as the external editor for Godot, so I found your repo but decided to give it a try with a different approach

[my take](https://github.com/vncsalencar/helix_godot/blob/5d8c4efe0644be974304eb9ca3205046c233e0d5/src/main.rs#L70-L82)
plus the following config on Godot
![image](https://github.com/Multirious/helix-win-runner/assets/42007303/f09d09f0-2b3f-4a3c-a49b-413300533f68)

I just spawn a alacritty.exe + hx.exe command with the arguments Godot provides when calling an external editor and it seems to work a-okay without having to wait for the automation/macro to run (though the repo is not really meant to be used by others as I haven't made it general, just wanted to quickly fix it for my issue)

But I got curious so I wanted to ask, if you don't mind, why'd you automate it instead?

**Comment by Multirious** [comment]
Ah sorry, I forgot to clarify how this solution came to be. It started from this [discussion](https://github.com/helix-editor/helix/discussions/6190). And also afaik connecting to Helix from external programs is not yet supported which have feature such as switching file, this script use macro to do that. This just solved my issue generally enough that I just stick with it. I'd love to update to a better solution! I've read your script briefly and it seems like your script only contains the launching part which my script actually **doesn't have**. Here my script aim to let user create their own launching script to let users use whatever terminal they want which of course have different configuration and connect that to my script with the flag `-e`, `--execute-path` flag. 

If Helix still doesn't support connection then I might update the script with copy-paste to fix the waiting issue.

I'll update the README to clarify what this thing solves.

**Comment by vncsalencar** [comment]
Yeah, makes sense @Multirious!
Unfortunately the missing piece would be https://github.com/helix-editor/helix/issues/312 for changing the buffer for a currently open helix instance. That is not in my requirements because I also use the working dir flag to open the Godot's project folder and then just use it to switch to whatever script or file I'd like directly from helix but it'd be great if I could tap the scripts or files from Godot and swap buffer in helix as well, so that totally makes sense.
Thanks for the reply! Hopefully when helix gets more features these will improve.
